name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm ci
      - run: npm run build

      - name: Install PHP
        run: apt-get update && apt-get install -y php

      - run: echo -e "my-first-vue-laravel-project\n2" | npm test
