name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm ci
      - run: npm run build

      # Install PHP (required by your script)
      - name: Install PHP
        run: apt-get update && apt-get install -y php

      # Install expect to simulate the interactive input
      - name: Install expect
        run: apt-get install -y expect

      # Use expect to provide multiple inputs interactively
      - name: Simulate interactive input using expect
        run: |
          expect <<EOF
          spawn npm test
          expect "Enter a project name (using default \"v-kit-app\" if left blank):"
          send "sample-proj\n"
          expect "Select your preferred boilerplate:"
          send "5\n"
          expect eof
          EOF
