name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci

      - name: Build the Project
        run: npm run build

      - name: Run Tests
        run: npm test
